name: Build and upload PDF to Github Release

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Build
      run: |
        npm install -g pnpm
        pnpm i
        pnpm run build

    - uses: xresloader/upload-to-github-release@main
      with:
        file: "out/*.pdf"
        branches: "master"
        tags: true
        verbose: true
        prerelease: true
